apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-frontend-to-access-backend
  namespace: blog-be
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: blog-fe
  to:
  - group: ""
    kind: Service
